### ISSUE TITLE
cron job check_site only update site w/ new site_id

### ISSUE THREAD

**Issue by yachang** [m-lab/mlab-ns#126] opened 2018-03-29 14:55 UTC
While if the information of an existing site got updated through json file, it will be ignored.

**Comment by nkinkade** [comment] 2018-03-30 15:37
This is likely a duplicate of #54. If so, please close this issue and add comments to that issue.

**Comment by nkinkade** [comment] 2018-06-19 23:06
Duplicate of #54. Closing.

**Closed by nkinkade** 2018-06-19 23:06 UTC
Labels: 2, P0, Sprint 9, Story
