### ISSUE TITLE
slice parsing fail for one tool if one site failed

### ISSUE THREAD

**Issue by yachang** [m-lab/mlab-ns#124] opened 2018-03-29 14:51 UTC
In cron job check status, there is failure 

Unable to parse Nagios sliver status. Nagios status missing or unparseable:  (/base/data/home/apps/s~mlab-ns/20180130t190229.407307574601921947/mlabns/util/nagios_status.py:163)

Which was caused by failed to parse the output from a stopped tool:

http://nagios.measurementlab.net/baseList?show_state=1&service_name=glasnost&plugin_output=1

While other tool is still working (such as NDT)

problem:

1. Log information is missing, which should report which URL is failing
2. For failed tool, report the reason (the whole file missing, or just one line(site) failed)

**Comment by yachang** [comment] 2018-03-29 15:37
With new log info, there are 3 failed urls:

http://nagios.measurementlab.net/baseList?show_state=1&service_name=glasnost&plugin_output=1
http://nagios.measurementlab.net/baseList?show_state=1&service_name=glasnost_ipv6&plugin_output=1

http://nagios.measurementlab.net/baseList?show_state=1&service_name=ndt_ipv6&plugin_output=1

The first 2 are expected.

But the last one (ndt_ipv6) need to be fixed.

**Comment by pboothe** [comment] 2018-03-29 15:43
Questions of note:
Are we constructing the baselist URL in the right way?
Is the baselist output accurately reflecting the state recorded by nagios?

Basically, all we know now is that that monitoring information is not properly making it into mlab-ns. We don't know:

- whether mlab-ns is making the request properly, 
- whether the system that handles requests is broken in this case, 
- whether nagios is broken in this case, or 
- whether we are getting true information about the state of ipv6 on the platform, and the information is "nothing works".

Depending on the root cause, we would need to do things differently, and this problem ends up being assigned to different people.

**Comment by nkinkade** [comment] 2018-03-30 15:29
The last failure, for ndt_ipv6, while it should be fixed, is expected. The service names map directly to Nagios service check names. There is no "ndt_ipv6" check in Nagios. That is, there are no IPv6 checks for NDT in Nagios, and none in Prometheus at the moment, though I just submitted two PRs to add that to Prometheus.

https://github.com/m-lab/operator/pull/216
https://github.com/m-lab/prometheus-support/pull/210

For the glasnost checks, we should probably manually remove those Tools from the datastore. They no longer exist in m-lab/operator/plsync/slices.py, and neither in the mlab-host-ips.txt nor mlab-site-stats.json. There is just no automated facility for removing datastore items for the kind "Tool" in the mlab-ns code.

**Comment by pboothe** [comment] 2018-03-30 15:35
It's a Friday, so let's remove stuff from datastore on Monday.

**Comment by nkinkade** [comment] 2018-03-30 15:55
Sounds good. Though it won't stop me from removing them from mlab-nstesting today! :) Also, those PRs were merged, so we now have IPv6 monitoring of NDT in Prometheus. Well, in mlab-sandbox and mlab-staging, until we deploy to production next week.

**Comment by pboothe** [comment] 2018-04-02 19:22
Glasnost has been removed from the datastore in testing (by Nathan) and prod (by Peter).

**Comment by nkinkade** [comment] 2018-06-19 23:07
This issue was resolved be removing Glasnost from the datastore. Closing issue.

**Closed by nkinkade** 2018-06-19 23:07 UTC
Labels: 2, P1, Sprint 9, Story
